name: Auto Builds

on:
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Download English Model
        run: ./download-model.sh

      - name: Build Unsigned APK
        run: bash ./gradlew :app:assembleRelease
        
      - name: Sign APK
        uses: Tlaster/android-sign@v1
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/app/build/release/signed/app-release.apk
