name: Auto Builds

on:
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      - name: Download Language Model
        run: ./scripts/english.sh

      - name: Build Unsigned APK
        run: bash ./gradlew :app:assembleRelease
        
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
          
      - name: Update Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: true
          name: Latest Version
          tag: rolling
          artifacts: ${{steps.sign_app.outputs.signedReleaseFile}}
          body: "This app uses a rolling release system, where no real releases exist and this page automatically updates with every new commit. Click the 'Assets' button if no APK link is visible"
          token: ${{ secrets.GITHUB_TOKEN }}
